name: lucerna
description: "Research Paper discovery tool"
publish_to: 'none'
version: 0.1.0
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts:
  font_awesome_flutter:
  flutter_riverpod:
  riverpod_annotation: 
  go_router:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  custom_lint:
  riverpod_generator:
  riverpod_lint:

flutter:
  uses-material-design: true