name: lucerna
description: "Research Paper discovery tool"
publish_to: 'none'
version: 0.1.0
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts:
  font_awesome_flutter:
  flutter_riverpod:
  riverpod_annotation: 
  go_router:
  freezed_annotation:
  json_annotation: ^4.9.0
  http: ^1.3.0
  flutter_svg:
  file_picker: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  custom_lint:
  riverpod_generator:
  riverpod_lint:
  freezed: ^3.0.4
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - assets/lucerna_logo.svg